name: Deploy to Firebase Hosting (gambling)

on:
  push:
    branches: [gambling]
    paths:
      - "public/**"
      - "firebase.json"
      - ".firebaserc"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy Hosting (Test)
        run: firebase hosting:channel:deploy gambling --only test --project mooreco-in --non-interactive --token "${{ secrets.FIREBASE_TOKEN }}"
