name: Deploy to Firebase Hosting (live on main)

on:
  push:
    branches: [main]
    paths:
      - "public/**"
      - "firebase.json"
      - ".firebaserc"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy Hosting
        run: firebase deploy --only hosting --project mooreco-in --non-interactive --token "${{ secrets.FIREBASE_TOKEN }}"
