name: Prettier Check
on:
  pull_request:
  push:
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # Use your devDependency, or just run npx without installing
      - run: npx prettier@latest --check .
